// Generated from App.jsx's React.lazy declarations + <Route path> entries.
// Regenerate whenever routes are added/renamed (see git history for the
// generator). A route missing here simply loses hover-prefetch and falls
// back to loading on click — nothing breaks.
//
// Route path -> chunk loader, mirroring the React.lazy declarations in
// App.jsx. Sidebar hover/focus fires these so the route chunk is already
// downloaded before the click; React then swaps the page without the
// startTransition hold that used to leave the old page on screen.
//
// Calling an entry twice is safe: the browser module cache dedupes it, and
// the same URL App.jsx imports resolves to the same module.

export const routeLoaders = {
  "/academic-sessions": () => import("../pages/AcademicSessions"),
  "/accountant": () => import("../pages/staff/AccountantDashboard"),
  "/accountant/fees": () => import("../pages/staff/Fees"),
  "/accounting": () => import("../pages/Accounting"),
  "/achievements": () => import("../pages/Achievements"),
  "/addstudent": () => import("../pages/AddStudent"),
  "/admission-counsellor": () => import("../pages/CounsellorWorkspace"),
  "/admission-enquiry": () => import("../pages/AdmissionEnquiry"),
  "/attendance": () => import("../pages/Attendance"),
  "/branches": () => import("../pages/Branches"),
  "/broadcast": () => import("../pages/Broadcast"),
  "/bus-tracking": () => import("../pages/BusTracking"),
  "/dashboard": () => import("../pages/Dashboard"),
  "/dev/icon-picker": () => import("../pages/IconPicker"),
  "/diary": () => import("../pages/Diary"),
  "/events": () => import("../pages/Events"),
  "/examination": () => import("../pages/Examination"),
  "/fees-collection": () => import("../pages/FeesCollection"),
  "/forgot-password": () => import("../pages/ForgotPassword"),
  "/grading-scales": () => import("../pages/GradingScales"),
  "/homework": () => import("../pages/Homework"),
  "/hostel": () => import("../pages/Hostel"),
  "/inventory": () => import("../pages/Inventory"),
  "/leave": () => import("../pages/Leave"),
  "/librarian": () => import("../pages/staff/LibrarianDashboard"),
  "/librarian/books": () => import("../pages/staff/Books"),
  "/librarian/circulation": () => import("../pages/staff/Circulation"),
  "/library": () => import("../pages/Library"),
  "/login": () => import("../pages/Login"),
  "/manage-school": () => import("../pages/ManageSchool"),
  "/marks-entry": () => import("../pages/MarksEntry"),
  "/messages": () => import("../pages/Messages"),
  "/notice-board": () => import("../pages/NoticeBoard"),
  "/notifications": () => import("../pages/Notifications"),
  "/online-payment": () => import("../pages/OnlinePayment"),
  "/parent-dashboard": () => import("../pages/ParentDashboard"),
  "/payment-gateway": () => import("../pages/PaymentGateway"),
  "/payroll": () => import("../pages/Payroll"),
  "/platform": () => import("../pages/platform/PlatformDashboard"),
  "/platform/audit": () => import("../pages/platform/AuditLogs"),
  "/platform/onboarding": () => import("../pages/platform/SchoolOnboarding"),
  "/platform/plans": () => import("../pages/Plans"),
  "/platform/reports": () => import("../pages/platform/PlatformReports"),
  "/platform/schools": () => import("../pages/platform/SchoolsManagement"),
  "/platform/schools/:id": () => import("../pages/platform/SchoolDetail"),
  "/platform/settings": () => import("../pages/platform/PlatformSettings"),
  "/platform/subscriptions": () => import("../pages/Subscriptions"),
  "/platform/users": () => import("../pages/platform/PlatformUsers"),
  "/profile": () => import("../pages/Account"),
  "/promotions": () => import("../pages/Promotions"),
  "/reception": () => import("../pages/staff/ReceptionDashboard"),
  "/reception/enquiries": () => import("../pages/staff/Enquiries"),
  "/reception/notices": () => import("../pages/staff/ReceptionNotices"),
  "/reception/student-lookup": () => import("../pages/staff/StudentLookup"),
  "/report-card": () => import("../pages/ReportCard"),
  "/reports": () => import("../pages/Reports"),
  "/reset-password": () => import("../pages/ResetPassword"),
  "/rollover": () => import("../pages/Rollover"),
  "/settings": () => import("../pages/SchoolSettings"),
  "/staff-dashboard": () => import("../pages/StaffDashboard"),
  "/staff/complete/:id": () => import("../pages/StaffCompleteProfile"),
  "/staff/my-attendance": () => import("../pages/MyAttendance"),
  "/my-work": () => import("../pages/MyWork"),
  "/staff/profile": () => import("../pages/staff/MyProfile"),
  "/student-dashboard": () => import("../pages/student/StudentDashboard"),
  "/student/achievements": () => import("../pages/student/Achievements"),
  "/student/attendance": () => import("../pages/student/Attendance"),
  "/student/documents": () => import("../pages/student/Documents"),
  "/student/events": () => import("../pages/student/Events"),
  "/student/exams": () => import("../pages/student/Exams"),
  "/student/fees": () => import("../pages/student/Fees"),
  "/student/homework": () => import("../pages/student/Homework"),
  "/student/hostel": () => import("../pages/student/Hostel"),
  "/student/leave": () => import("../pages/student/Leave"),
  "/student/library": () => import("../pages/student/Library"),
  "/student/notices": () => import("../pages/student/Notices"),
  "/student/notifications": () => import("../pages/student/Notifications"),
  "/student/profile": () => import("../pages/student/Profile"),
  "/student/results": () => import("../pages/student/Results"),
  "/student/study-materials": () => import("../pages/student/StudyMaterials"),
  "/student/syllabus": () => import("../pages/student/Syllabus"),
  "/student/timetable": () => import("../pages/student/Timetable"),
  "/student/transport": () => import("../pages/student/Transport"),
  "/students": () => import("../pages/Students"),
  "/students/complete/:id": () => import("../pages/StudentCompleteProfile"),
  "/study-materials": () => import("../pages/StudyMaterials"),
  "/subscription": () => import("../pages/Subscription"),
  "/syllabus": () => import("../pages/SyllabusManage"),
  "/teacher-dashboard": () => import("../pages/TeacherDashboard"),
  "/teacher/attendance": () => import("../pages/teacher/Attendance"),
  "/teacher/exams": () => import("../pages/teacher/Exams"),
  "/teacher/homework": () => import("../pages/teacher/Homework"),
  "/teacher/my-class": () => import("../pages/teacher/MyClass"),
  "/teacher/notices": () => import("../pages/teacher/Notices"),
  "/teacher/performance": () => import("../pages/teacher/Performance"),
  "/teacher/profile": () => import("../pages/teacher/Profile"),
  "/teacher/timetable": () => import("../pages/teacher/Timetable"),
  "/teachers": () => import("../pages/Teachers"),
  "/timetable": () => import("../pages/Timetable"),
  "/transfers": () => import("../pages/Transfers"),
  "/transport": () => import("../pages/staff/TransportDashboard"),
  "/transport/allocations": () => import("../pages/staff/Allocations"),
  "/transport/routes": () => import("../pages/staff/BusRoutes"),
  "/users": () => import("../pages/Users"),
};

// Kick off a route's chunk without waiting for the result. Unknown paths
// (guest links, routes without a lazy page) are a no-op.
export function prefetchRoute(pathname) {
  const load = routeLoaders[pathname];
  if (load) load();
}
